<template>
  <main>
    <h3>Popup Page</h3>

    <div class="calc">
      <button @click="minus" :disabled="count <= 0">-</button>
      <label>{{ count }}</label>
      <button @click="add">+</button>
    </div>

    <a :href="link" target="_blank"> generated by create-chrome-ext </a>
    <el-button type="primary" plain @click="getDanmuData">获取弹幕列表信息</el-button>
    <div>
      <el-input v-model="iframeCode" placeholder="Enter iframe code" />
      <el-button type="primary" plain @click="getCid">Extract Cid</el-button>
      <div>
        <label>Extracted Cid:</label>
        <div>{{ extractedCid }}</div>
      </div>
      <div v-if="comments && comments.length">
        <label>Comments:</label>
        <ul>
          <li v-for="(comment, index) in comments" :key="index">
            <div>
              <strong>Content:</strong> {{ comment.content }}<br>
              <strong>Time:</strong> {{ comment.time }} seconds<br>
              <strong>Mode:</strong> {{ comment.mode }}<br>
              <strong>Font Size:</strong> {{ comment.fontSize }}<br>
              <strong>Color:</strong> {{ comment.color }}<br>
              <strong>Timestamp:</strong> {{ comment.timestamp }}<br>
              <strong>Pool:</strong> {{ comment.pool }}<br>
              <strong>Sender ID:</strong> {{ comment.senderId }}<br>
              <strong>Row ID:</strong> {{ comment.rowId }}
            </div>
          </li>
        </ul>
      </div>
      <div v-else>No comments available</div>
    </div>
  </main>
</template>


<script setup lang="js">
import { ref, watch, onMounted, onUnmounted } from 'vue'
// 导入 Element UI 的按钮组件
import { ElButton } from 'element-plus';

const count = ref(0)
const link = ref('https://github.com/guocaoyi/create-chrome-ext')

const minus = () => {
  if (count.value > 0) count.value--
}
const add = () => count.value++

onMounted(() => {
  chrome.storage.sync.get(['count'], (result) => {
    count.value = result.count || 0
  })
})

watch(count, (newCount) => {
  chrome.storage.sync.set({ count: newCount })

  chrome.runtime.sendMessage({ type: 'COUNT', count: count.value })
})

// 执行获取弹幕信息并发送的逻辑
const getDanmuData = () => {
  // 查询当前活动标签页
  chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    const activeTab = tabs[0];
    // 使用 chrome.scripting.executeScript
    chrome.scripting.executeScript({
      target: { tabId: activeTab.id },
      function: () => {

        // 获取视频标题数据
        let danmuTitle = "hello";
        const danmuTitleElement = document.querySelector('#viewbox_report > h1');

        if (danmuTitleElement) {
          danmuTitle = danmuTitleElement.innerText;
        } else {
          danmuTitle = '未找到视频标题数据';
        }

        // 获取弹幕列表
        const danmuListElement = document.querySelector('div.bui-long-list-wrap');

        // 获取可滚动元素的总高度
        let totalHeight = 0;

        // 安全判断
        if (danmuListElement) {
          // 获取可滚动元素的总高度
          totalHeight = danmuListElement.scrollHeight;
        }

        // 模拟滚动函数
        const simulateScroll = () => {

          if (danmuListElement) {
            // 创建鼠标滚轮事件
            const wheelEvent = new WheelEvent('wheel', {
              bubbles: true,
              cancelable: true,
              view: window,
              deltaY: 24 * 14, // 适当调整滚动距离
            });

            // 触发滚轮事件
            danmuListElement.dispatchEvent(wheelEvent);
            // console.log('模拟滚动事件成功');

          } else {
            console.log('未找到可滚动元素');
          }
        };

        // 弹幕时间
        let danmuTimeElements = document.querySelectorAll('li > div > span.dm-info-time');
        let danmuTimes = [];

        // 弹幕内容
        let danmuContentElements = document.querySelectorAll('li > div > span.dm-info-dm');
        let danmuContents = [];

        // 弹幕日期
        let danmuDateElements = document.querySelectorAll('li > div > span.dm-info-date');
        let danmuDates = [];

        // 模拟滚动多次，以确保加载更多的弹幕
        for (let i = 0; i < totalHeight / 24 / 14; i++) {
          simulateScroll();

          // 获取弹幕时间
          danmuTimeElements = document.querySelectorAll('li > div > span.dm-info-time');

          danmuTimeElements.forEach((element) => {
            danmuTimes.push(element.innerText);
          });
          if (danmuTimes) {
            // console.log('弹幕时间列表:', danmuTimes);
          } else {
            console.log('未找到弹幕时间列表');
          }

          // 获取弹幕内容
          danmuContentElements = document.querySelectorAll('li > div > span.dm-info-dm');

          danmuContentElements.forEach((element) => {
            danmuContents.push(element.innerText);
          });
          if (danmuContents) {
            // console.log('弹幕内容列表:', danmuContents);
          } else {
            console.log('未找到弹幕内容列表');
          }

          // 获取弹幕日期
          danmuDateElements = document.querySelectorAll('li > div > span.dm-info-date');

          danmuDateElements.forEach((element) => {
            danmuDates.push(element.innerText);
          });
          if (danmuDates) {
            // console.log('弹幕日期列表:', danmuDates);
          } else {
            console.log('未找到弹幕日期列表');
          }
        }

        // 向 Background Script 发送弹幕数据
        chrome.runtime.sendMessage({ type: 'danmuData', titledata: danmuTitle, timedata: danmuTimes, contentdata: danmuContents, datedata: danmuDates });
      },
    });
  });
};

const iframeCode = ref("");
const extractedCid = ref("");
const comments = ref("");

const getCid = () => {
  const regex = /cid=(\d+)/;
  const match = iframeCode.value.match(regex);

  if (match && match[1]) {
    extractedCid.value = match[1];
    console.log("Extracted Cid:", match[1]);

    // 根据提取到的 cid 获取评论内容
    fetchComments(match[1]);
  } else {
    console.error("Unable to extract Cid from iframe code");
  }
};

const fetchComments = async (cid) => {
  const url = `https://comment.bilibili.com/${cid}.xml`;

  try {
    const response = await fetch(url);
    const xmlData = await response.text();

    // 解析XML数据
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlData, "text/xml");
    const commentNodes = xmlDoc.querySelectorAll('d');

    // 将解析的评论数据放入 comments 数组中
    comments.value = Array.from(commentNodes).map((node) => {
      return {
        content: node.textContent,
        time: parseFloat(node.getAttribute('p').split(',')[0]), // 解析时间参数
        mode: parseInt(node.getAttribute('p').split(',')[1]),
        fontSize: parseInt(node.getAttribute('p').split(',')[2]),
        color: parseInt(node.getAttribute('p').split(',')[3]),
        timestamp: parseInt(node.getAttribute('p').split(',')[4]),
        pool: parseInt(node.getAttribute('p').split(',')[5]),
        senderId: node.getAttribute('p').split(',')[6],
        rowId: parseInt(node.getAttribute('p').split(',')[7])
      };
    });

    console.log("Comments:", comments);

    // 初始化空数组
    const contents = [];
    const times = [];
    const modes = [];
    const fontSizes = [];
    const colors = [];
    const timestamps = [];
    const pools = [];
    const senderIds = [];
    const rowIds = [];

    // 使用 forEach 遍历 comments 数组
    comments.value.forEach((comment) => {
      // 将每个字段的值分别存储在对应的数组中
      contents.push(comment.content);
      times.push(comment.time);
      modes.push(comment.mode);
      fontSizes.push(comment.fontSize);
      colors.push(comment.color);
      timestamps.push(comment.timestamp);
      pools.push(comment.pool);
      senderIds.push(comment.senderId);
      rowIds.push(comment.rowId);
    });

    // 向 Background Script 发送弹幕数据
    chrome.runtime.sendMessage({
      type: 'danmuFullData', contents: contents, times: times, modes: modes, fontSizes: fontSizes,
      colors: colors, timestamps: timestamps, pools: pools, senderIds: senderIds, rowIds: rowIds
    });
  } catch (error) {
    console.error("Error fetching comments", error);
    comments.value = []; // 清空评论内容
  }
};

</script>

<style>
:root {
  font-family:
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    'Segoe UI',
    Roboto,
    Oxygen,
    Ubuntu,
    Cantarell,
    'Open Sans',
    'Helvetica Neue',
    sans-serif;

  color-scheme: light dark;
  background-color: #242424;
}

@media (prefers-color-scheme: light) {
  :root {
    background-color: #fafafa;
  }

  a:hover {
    color: #42b983;
  }
}

body {
  min-width: 20rem;
  color-scheme: light dark;
}

main {
  text-align: center;
  padding: 1em;
  margin: 0 auto;
}

h3 {
  color: #42b983;
  text-transform: uppercase;
  font-size: 1.5rem;
  font-weight: 200;
  line-height: 1.2rem;
  margin: 2rem auto;
}

.calc {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 2rem;

  >button {
    font-size: 1rem;
    padding: 0.5rem 1rem;
    border: 1px solid #42b983;
    border-radius: 0.25rem;
    background-color: transparent;
    color: #42b983;
    cursor: pointer;
    outline: none;

    width: 3rem;
    margin: 0 a;
  }

  >label {
    font-size: 1.5rem;
    margin: 0 1rem;
  }
}

a {
  font-size: 0.5rem;
  margin: 0.5rem;
  color: #cccccc;
  text-decoration: none;
}
</style>
