<template>
  <main>
    <h3>Popup Page</h3>

    <div class="calc">
      <button @click="minus" :disabled="count <= 0">-</button>
      <label>{{ count }}</label>
      <button @click="add">+</button>
    </div>

    <a :href="link" target="_blank"> generated by create-chrome-ext </a>
    <el-button type="primary" plain @click="getDanmuData">获取弹幕信息</el-button>
  </main>
</template>


<script setup lang="js">
import { ref, watch, onMounted, onUnmounted } from 'vue'
// 导入 Element UI 的按钮组件
import { ElButton } from 'element-plus';

const count = ref(0)
const link = ref('https://github.com/guocaoyi/create-chrome-ext')

const minus = () => {
  if (count.value > 0) count.value--
}
const add = () => count.value++

onMounted(() => {
  chrome.storage.sync.get(['count'], (result) => {
    count.value = result.count || 0
  })
})

watch(count, (newCount) => {
  chrome.storage.sync.set({ count: newCount })

  chrome.runtime.sendMessage({ type: 'COUNT', count: count.value })
})

// 执行获取弹幕信息并发送的逻辑
const getDanmuData = () => {
  // 查询当前活动标签页
  chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    const activeTab = tabs[0];
    // 使用 chrome.scripting.executeScript
    chrome.scripting.executeScript({
      target: { tabId: activeTab.id },
      function: () => {

        // 获取视频标题数据
        let danmuTitle = "hello";
        const danmuTitleElement = document.querySelector('#viewbox_report > h1');

        if (danmuTitleElement) {
          danmuTitle = danmuTitleElement.innerText;
        } else {
          danmuTitle = '未找到视频标题数据';
        }

        // 获取弹幕列表
        const danmuListElement = document.querySelector('div.bui-long-list-wrap');

        // 获取可滚动元素的总高度
        let totalHeight = 0;

        // 安全判断
        if (danmuListElement) {
          // 获取可滚动元素的总高度
          totalHeight = danmuListElement.scrollHeight;
        }

        // 模拟滚动函数
        const simulateScroll = () => {

          if (danmuListElement) {
            // 创建鼠标滚轮事件
            const wheelEvent = new WheelEvent('wheel', {
              bubbles: true,
              cancelable: true,
              view: window,
              deltaY: 24 * 14, // 适当调整滚动距离
            });

            // 触发滚轮事件
            danmuListElement.dispatchEvent(wheelEvent);
            // console.log('模拟滚动事件成功');

          } else {
            console.log('未找到可滚动元素');
          }
        };

        // 弹幕时间
        let danmuTimeElements = document.querySelectorAll('li > div > span.dm-info-time');
        let danmuTimes = [];

        // 弹幕内容
        let danmuContentElements = document.querySelectorAll('li > div > span.dm-info-dm');
        let danmuContents = [];

        // 弹幕日期
        let danmuDateElements = document.querySelectorAll('li > div > span.dm-info-date');
        let danmuDates = [];

        // 模拟滚动多次，以确保加载更多的弹幕
        for (let i = 0; i < totalHeight / 24 / 14; i++) {
          simulateScroll();

          // 获取弹幕时间
          danmuTimeElements = document.querySelectorAll('li > div > span.dm-info-time');

          danmuTimeElements.forEach((element) => {
            danmuTimes.push(element.innerText);
          });
          if (danmuTimes) {
            // console.log('弹幕时间列表:', danmuTimes);
          } else {
            console.log('未找到弹幕时间列表');
          }

          // 获取弹幕内容
          danmuContentElements = document.querySelectorAll('li > div > span.dm-info-dm');

          danmuContentElements.forEach((element) => {
            danmuContents.push(element.innerText);
          });
          if (danmuContents) {
            // console.log('弹幕内容列表:', danmuContents);
          } else {
            console.log('未找到弹幕内容列表');
          }

          // 获取弹幕日期
          danmuDateElements = document.querySelectorAll('li > div > span.dm-info-date');

          danmuDateElements.forEach((element) => {
            danmuDates.push(element.innerText);
          });
          if (danmuDates) {
            // console.log('弹幕日期列表:', danmuDates);
          } else {
            console.log('未找到弹幕日期列表');
          }
        }

        // 向 Background Script 发送弹幕数据
        chrome.runtime.sendMessage({ type: 'danmuData', titledata: danmuTitle, timedata: danmuTimes, contentdata: danmuContents, datedata: danmuDates });
      },
    });
  });
};




</script>

<style>
:root {
  font-family:
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    'Segoe UI',
    Roboto,
    Oxygen,
    Ubuntu,
    Cantarell,
    'Open Sans',
    'Helvetica Neue',
    sans-serif;

  color-scheme: light dark;
  background-color: #242424;
}

@media (prefers-color-scheme: light) {
  :root {
    background-color: #fafafa;
  }

  a:hover {
    color: #42b983;
  }
}

body {
  min-width: 20rem;
  color-scheme: light dark;
}

main {
  text-align: center;
  padding: 1em;
  margin: 0 auto;
}

h3 {
  color: #42b983;
  text-transform: uppercase;
  font-size: 1.5rem;
  font-weight: 200;
  line-height: 1.2rem;
  margin: 2rem auto;
}

.calc {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 2rem;

  >button {
    font-size: 1rem;
    padding: 0.5rem 1rem;
    border: 1px solid #42b983;
    border-radius: 0.25rem;
    background-color: transparent;
    color: #42b983;
    cursor: pointer;
    outline: none;

    width: 3rem;
    margin: 0 a;
  }

  >label {
    font-size: 1.5rem;
    margin: 0 1rem;
  }
}

a {
  font-size: 0.5rem;
  margin: 0.5rem;
  color: #cccccc;
  text-decoration: none;
}
</style>
