<script setup lang="js">
import { ref, onMounted } from 'vue'

const countSync = ref(0)
const link = ref('https://github.com/guocaoyi/create-chrome-ext')

onMounted(() => {
  chrome.storage.sync.get(['count'], (result) => {
    countSync.value = result.count || 0
  })

  chrome.runtime.onMessage.addListener((request) => {
    if (request.type === 'COUNT') {
      countSync.value = request?.count ?? 0
    }
  })
})

const goBack = () => {
  // 返回浏览器的上一个页面
  window.history.back();
}
</script>

<template>
  <main>
    <div class="center-container">
      <h3>Options Page</h3>
  
      <h4>Count from Popup: {{ countSync }}</h4>
  
      <button @click="goBack">Return</button>
    </div>

    <div class="center-container">
      <a :href="link" target="_blank">generated by create-chrome-ext</a>
    </div>
  </main>
</template>

<style>
:root {
  font-family:
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    'Segoe UI',
    Roboto,
    Oxygen,
    Ubuntu,
    Cantarell,
    'Open Sans',
    'Helvetica Neue',
    sans-serif;

  color-scheme: light dark;
  background-color: #242424;
}

@media (prefers-color-scheme: light) {
  :root {
    background-color: #fafafa;
  }

  a:hover {
    color: #42b983;
  }
}

body {
  min-width: 20rem;
}

main {
  text-align: center;
  padding: 1em;
  margin: 0 auto;
}

.center-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin-bottom: 1rem; /* 添加间距，防止按钮和链接挨得太近 */
}

h3 {
  color: #42b983;
  text-transform: uppercase;
  font-size: 1.5rem;
  font-weight: 200;
  line-height: 1.2rem;
  margin: 2rem auto;
}

button {
  margin: 1rem;
  padding: 0.5rem 1rem;
  font-size: 1rem;
  background-color: #42b983;
  color: #fff;
  border: none;
  cursor: pointer;
}

button:hover {
  background-color: #218c70;
}

a {
  font-size: 0.5rem;
  margin: 0.5rem;
  color: #cccccc;
  text-decoration: none;
}
</style>
